// <auto-generated />
namespace FitnessWebApi.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MicronutrientsTableAddedCategoryColumnInFoodsAddedManyToManyAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MicronutrientsTableAddedCategoryColumnInFoodsAddedManyToManyAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201711161118551_MicronutrientsTableAddedCategoryColumnInFoodsAddedManyToManyAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
